from django.db import models

class Order(models.Model):
    supplier_name = models.CharField(max_length=255)
    buyer_name = models.CharField(max_length=255)
    master_order_no = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to="order_images/", null=True, blank=True)
    customer = models.CharField(max_length=255)
    order_no = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    items = models.PositiveIntegerField()
    total_value = models.DecimalField(max_digits=10, decimal_places=2)
    shipped = models.BooleanField(default=False)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    qty = models.PositiveIntegerField()
    shipment_date = models.DateField()
    season_year = models.CharField(max_length=20)
    ref_no = models.CharField(max_length=255)
    factory_shipment = models.CharField(max_length=255)
    remarks = models.TextField(null=True, blank=True)
    garment = models.CharField(max_length=255)
    fabrication = models.CharField(max_length=255)
    fabric_weight = models.DecimalField(max_digits=6, decimal_places=2)
    wash_description = models.TextField(null=True, blank=True)
    genders = models.CharField(max_length=50)
    color = models.CharField(max_length=100)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    size_range = models.CharField(max_length=100)
    selling_price = models.DecimalField(max_digits=10, decimal_places=2)
    price_in_dz = models.DecimalField(max_digits=10, decimal_places=2)
    commission = models.DecimalField(max_digits=10, decimal_places=2)
    department = models.CharField(max_length=255)
    purchase_order_received_date = models.DateField()
    tech_receive_date = models.DateField(null=True, blank=True)
    lc_received_date = models.DateField(null=True, blank=True)
    pi_sent_date = models.DateField(null=True, blank=True)
    cargo_handover_date = models.DateField(null=True, blank=True)
    current_status = models.CharField(max_length=255)
    ic_issue_date = models.DateField(null=True, blank=True)
    commission_received_date = models.DateField(null=True, blank=True)
    invoice_no = models.CharField(max_length=255, unique=True)
    shipped_by = models.CharField(max_length=255)
    processed_by = models.CharField(max_length=255)
    discount = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    shipped_qty = models.PositiveIntegerField()
    invoice_amount = models.DecimalField(max_digits=10, decimal_places=2)
    final_inspection_date = models.DateField(null=True, blank=True)
    ex_factory_date = models.DateField(null=True, blank=True)
    etd_date = models.DateField(null=True, blank=True)
    eta_date = models.DateField(null=True, blank=True)
    remarks_2 = models.TextField(null=True, blank=True)
    no_of_catron = models.PositiveIntegerField(null=True, blank=True)
    remarks_3 = models.TextField(null=True, blank=True)
    leadtime = models.PositiveIntegerField(null=True, blank=True)
    line_allocation = models.CharField(max_length=255, null=True, blank=True)
    line_name = models.CharField(max_length=255, null=True, blank=True)
    wgr = models.DecimalField(max_digits=6, decimal_places=2)
    input = models.PositiveIntegerField()
    output = models.PositiveIntegerField()
