# Generated by Django 4.2 on 2024-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_no', models.CharField(max_length=255, unique=True)),
                ('request_qty', models.PositiveIntegerField()),
                ('proposed_shipment_date', models.DateField()),
                ('inquiry_received_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('proposed_supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fob_in_pcs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fob_in_dz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_1_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_2_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabric_3_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_accessories_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('print_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wash_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emb_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commercial_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('test_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zipper_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thread_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('label_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hangtag_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('care_label_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addition_label_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('button_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
