# Generated by Django 4.2 on 2024-11-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InquiryDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_inquiry', to='InquiryDatabase.inquiry')),
            ],
        ),
    ]
