# Generated by Django 4.2 on 2024-12-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InquiryDatabase', '0001_initial'),
        ('TotalInquiryList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalinquiry',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_inquiry', to='InquiryDatabase.inquiry', to_field='inquiry_no'),
        ),
    ]
