# Generated by Django 4.2 on 2024-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('master_order_no', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('customer', models.CharField(max_length=255)),
                ('order_no', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('items', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipped', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('shipment_date', models.DateField()),
                ('season_year', models.CharField(max_length=20)),
                ('ref_no', models.CharField(max_length=255)),
                ('factory_shipment', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('garment', models.CharField(max_length=255)),
                ('fabrication', models.CharField(max_length=255)),
                ('fabric_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wash_description', models.TextField(blank=True, null=True)),
                ('genders', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_range', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_in_dz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=255)),
                ('purchase_order_received_date', models.DateField()),
                ('tech_receive_date', models.DateField(blank=True, null=True)),
                ('lc_received_date', models.DateField(blank=True, null=True)),
                ('pi_sent_date', models.DateField(blank=True, null=True)),
                ('cargo_handover_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(max_length=255)),
                ('ic_issue_date', models.DateField(blank=True, null=True)),
                ('commission_received_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(max_length=255, unique=True)),
                ('shipped_by', models.CharField(max_length=255)),
                ('processed_by', models.CharField(max_length=255)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipped_qty', models.PositiveIntegerField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_inspection_date', models.DateField(blank=True, null=True)),
                ('ex_factory_date', models.DateField(blank=True, null=True)),
                ('etd_date', models.DateField(blank=True, null=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('remarks_2', models.TextField(blank=True, null=True)),
                ('no_of_catron', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks_3', models.TextField(blank=True, null=True)),
                ('leadtime', models.PositiveIntegerField(blank=True, null=True)),
                ('line_allocation', models.CharField(blank=True, max_length=255, null=True)),
                ('line_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wgr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('input', models.PositiveIntegerField()),
                ('output', models.PositiveIntegerField()),
            ],
        ),
    ]
